Add OpenBLAS support and enable static linking of LAPACKE (#2134)
i made changes to support cholesky2 from npbenchmarks, as it failed with
an undefined reference to LAPACKE and I don’t have
BLAS and LAPACKE installed as shared libs.
- added support for OpenBLAS if it is installed on the system
- allowed static linking by including LAPACKE, LAPACK, BLAS, and
gfortran in the link list
- updated cmake_libraries to be a list as the order of linking matters

---------

Co-authored-by: Yakup Koray Budanaz <budanaz.yakup@gmail.com>